apiVersion: apps/v1
kind: Deployment 
metadata:
  name: jenkins-deploy 
  labels:
    app: jenkins
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkinscontainer
          image: nikkoworld/nikkoimg
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec: 
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - port: 8070
      targetPort: 3000
