apiVersion: apps/v1
kind: Deployment 
metadata:
  name: portfolio-deployment 
  labels:
    app: portfolio
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: nodeazuredevops.azurecr.io/girija-sugumar/nodeapp
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: portfolio-service
  labels:
    app: portfolio
spec:
  type: LoadBalancer 
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 3000
